/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fatec.jpa.eventoapp;

import fatec.jpa.eventoapp.dao.EventDaoJpa;
import fatec.jpa.eventoapp.dao.NoticeDaoJpa;
import fatec.jpa.eventoapp.dao.UserDaoJpa;
import fatec.jpa.eventoapp.entity.*;
import fatec.jpa.eventoapp.enums.ModeratorLevelEnum;
import org.flywaydb.core.Flyway;

import javax.persistence.EntityManager;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Flyway flyway = Flyway
                .configure()
                .dataSource("jdbc:mysql://localhost:3306/fatec_db", "root", "password")
                .locations("classpath:db/migration")
                .load();

        flyway.clean();
        flyway.migrate();

        EntityManager manager = PersistenceManager.getInstance().getEntityManager();
        UserDaoJpa userDaoJpa = new UserDaoJpa(manager);
        User user = userDaoJpa.create("jabinho", "senha");

        EventDaoJpa eventDaoJpa = new EventDaoJpa(manager);

        PrivateEvent privateEvent = (PrivateEvent) eventDaoJpa.create(new PrivateEvent(), "Privado", new Date(System.currentTimeMillis()));
        PublicEvent publicEvent = (PublicEvent) eventDaoJpa.create(new PublicEvent(), "Publico", new Date(System.currentTimeMillis()));

        NoticeDaoJpa noticeDaoJpa = new NoticeDaoJpa(manager);
        noticeDaoJpa.create("Primeiro aviso", "Algum aviso", publicEvent);

        List<Event> eventList = new ArrayList<>();
        eventList.add(publicEvent);
        eventList.add(privateEvent);

        user.setEvents(eventList);
        userDaoJpa.save(user);

        userDaoJpa.create("Juquinha",  "senha", ModeratorLevelEnum.MANAGER);

        List<Notice> notices = userDaoJpa.getNoticesFromFutureUserEvents(user);
        for (Notice notice : notices) System.out.printf(notice.toString());

        //eventDaoJpa.delete(publicEvent);
    }
}
